### ISSUE TITLE
Should the datapackage name come from the URL or datapackage.json?

### ISSUE THREAD

**Issue by morty** [okfn/datapackage-identifier#1]
The datapackage.json spec has a name field, however this module chooses the name based on the end of the URL with datapackage.json removed:

https://github.com/okfn/datapackage-identifier/blob/master/index.js#L37

When dpm prints out the tree view it uses the name from the datapackage.json file rather than the one that comes from this library.

**Comment by rufuspollock** [comment]
@morty this is a good question though the answer here I think is "no" since datapackage-identifier does not parse datapackage.json so this behaviour should stay the same. However we should fix things in dpm.
