### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by waylonflinn** [okfn/datapackage-identifier#3]
I'd like to use the functionality in the recent PR I submitted (#2). I can do this with `npm link`, but it sure would be nice to get it straight from `npm`.

Can we get a new release published to `npm`, pretty please? :smile:

**Comment by rufuspollock** [comment]
@waylonflinn great point. Will get this up asap.

**Comment by rufuspollock** [comment]
FIXED. https://www.npmjs.com/package/datapackage-identifier
